name: tests-auth

on:
  pull_request:
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
        working-directory: ./auth
      - name: Run Tests
        run: npm run test:ci
        working-directory: ./auth