name: tests

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./path-to-auth-directory/auth
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run test:ci