name: tests-payments

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
        working-directory: ./payments
      - name: Run Tests
        run: npm run test:ci
        working-directory: ./payments